const Actions = {
  API_CALL_REQUEST: "API_CALL_REQUEST",
  API_CALL_SUCCESS: "API_CALL_SUCCESS",
  API_CALL_FAILURE: "API_CALL_FAILURE",
  API_CREATE_REQUEST: "USER_CREATE_REQUEST",
  USER_CREATE_SUCCESS: "USER_CREATE_SUCCESS",
  USER_CREATE_FAILURE: "USER_CREATE_FAILURE",
  API_POKEMONS_REQUEST: "API_POKEMONS_REQUEST",
  API_POKEMONS_SUCCESS: "API_POKEMONS_SUCCESS",
  API_POKEMONS_FAILURE: "API_POKEMONS_FAILURE",
  API_POKEMON_SHOW_REQUEST: "API_POKEMON_SHOW_REQUEST",
  API_POKEMON_SHOW_SUCCESS: "API_POKEMON_SHOW_SUCCESS",
  API_POKEMON_SHOW_FAILURE: "API_POKEMON_SHOW_FAILURE"

};
export default Actions;
